######################################################################
#
# File name : Top_Level_Module_V2_TB_compile.do
# Created on: Thu Jan 04 23:31:33 +0530 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib work
vlib msim

vlib msim/xil_defaultlib

vmap xil_defaultlib msim/xil_defaultlib

vcom -64 -93 -work xil_defaultlib  \
"../VHDL_Sources/constants.vhd" \
"../VHDL_Sources/HW_Calculator_V2.vhd" \
"../VHDL_Sources/Position_Output_Module.vhd" \
"../VHDL_Sources/classio.vhd" \
"../VHDL_Sources/Top_Level_Module_V2.vhd" \
"../VHDL_Sources/Top_Level_Module_V2_TB.vhd" \

