######################################################################
#
# File name : Top_Level_Module_V2_TB_wave.do
# Created on: Tue Jan 02 12:53:03 +0530 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
